/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazon;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import java.util.Iterator;
import java.util.LinkedList;

public class App {

    public static void main(String[] args) {

        LinkedList<Integer> l1 = new LinkedList<Integer>();
        l1.add(1);
        l1.add(4);
        l1.add(5);

        LinkedList<Integer> l2 = new LinkedList<Integer>();
        l2.add(2);

        Iterator i1 = l1.iterator();
        Iterator i2 = l2.iterator();

        Integer n1 = l1.getFirst();
        Integer n2 = l2.getFirst();

        LinkedList test = new LinkedList<Iterator>();

        while (i1.hasNext() && i2.hasNext()) {

            if ( (int) i1.next() < (int) i2.next()) {

            }

        }

    }

}
