/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazon;

import org.w3c.dom.NodeList;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {

        LinkedList l1 = new LinkedList();

        l1.add(2);
        l1.add(1);



    }




}
