/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

public class App {

    public static void main(String[] args) {
        int[] testArr = {4,5,6,7,0,2,1,3};
        int[] testArr2 = {0,1,2};
        System.out.println(restoreString("codeleet",testArr ));
        System.out.println(restoreString("abc",testArr2 ));
    }

    public static String restoreString (String s, int[] indices) {
        char[] arr = new char[indices.length];
        for (int i = 0; i < indices.length; i++) {
            arr[indices[i] ] = s.charAt(i);
        }
        return new String(arr);
    }
}
